name: sporadic
markdown: kramdown
pygments: true
title: sporadic
email: peter.alan.gao@gmail.com
twitter_username: peteragao
github_username:  peteragao
description: 
baseurl: ""
url: "http://peteragao.github.io"
permalink: pretty