# Site settings
title: sporadic
email: peter.alan.gao@gmail.com
description: 
baseurl: ""
url: "http://peteragao.github.io"
twitter_username: peteragao
github_username:  peteragao

# Build settings
markdown: kramdown
permalink: pretty
