project:
  type: website
  output-dir: docs

website:
  title: "PETER A. GAO"
  navbar:
    background: light
    foreground: dark
    right:
      - href: about.qmd
        text: ABOUT
      - href: teaching.qmd
        text: TEACHING
      - href: research.qmd
        text: RESEARCH
      - href: blog.qmd
        text: BLOG

format:
  html:
    theme: styles.scss
    css: styles.css



